language: node_js
node_js:
    - "0.12.7"
sudo: false
install:
    - npm install -g tslint typescript tsd
    - npm install
    - tsd install
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
    - tslint --version
    - tslint $(git ls-files | grep '.ts$')
    - tsc --version
    - tsc -p src/browser
    - tsc src/renderer/*.ts --out build/src/renderer
    - tsc -p tests/browser
    - npm test -- --travis
addons:
    apt:
        packages:
            - xvfb
